language: php

matrix:
  include:
    - php: 7.0
      env: DEPS="--prefer-lowest --prefer-stable" COVERALLS=""
    - php: 7.0
      env: DEPS="" COVERALLS=""
    - php: 7.1
      env: DEPS="--prefer-lowest --prefer-stable" COVERALLS=""
    - php: 7.1
      env: DEPS="" COVERALLS=""
    - php: 7.2
      env: DEPS="--prefer-lowest --prefer-stable" COVERALLS=""
    - php: 7.2
      env: DEPS="" COVERALLS=true
    - php: nightly
      env: DEPS="" COVERALLS=""
  allow_failures:
    - php: nightly
      env: DEPS="" COVERALLS=""
    - php: 7.1
      env: DEPS="--prefer-lowest --prefer-stable" COVERALLS=""

cache:
  directories:
    - ./vendor

before_install:
    # determine INI file
    - export INI_DIR=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - export INI=$INI_DIR/travis.ini
    # disable default memory limit
    - echo memory_limit = 2G >> $INI
    - if [[ $COVERALLS = "" && -f $INI_DIR/xdebug.ini ]]; then phpenv config-rm xdebug.ini; fi

install:
  - composer --prefer-source $DEPS update

script:
  - vendor/bin/phpunit
  - ./psalm --find-dead-code
  - vendor/bin/phpcs

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

deploy: # on tag builds with lowest php version and lowest deps
  skip_cleanup: true
  on:
    tags: true
    php: 7.0
    condition: "$DEPS"
  provider: releases
  api_key:
    secure: bduWzuD51MVgE0jFENamNZPBuU0OsLTCNNu85xB+PNZQQvavCPc6YSQmnavk+HiwiiUDVYGenF/18IL/yz0TU+yjJ/DYJIrdT/eAq5vUZqeORoc2XdzO6EWnCwR8F7xYwlIxkmewrie0+frabi/wQ/OPGF+zmR0uuGBrkJSAd3m6EnLwJ+8vdJ5uf3VdfB61iTmByEA5ehvRUI7R1GbBSBYX09F6tcaZTk17GDQA/vCNAlxNG/MWZZWta3unqX97N/XcgBdh+AcZY4WqjiIHUctqj0DzfJyo9CHgz9u4UT1a56ZmQWXSWSgstTXfSEnle7wO1NsRIfzvzUB0dGlBi9EOYQko5kkC4Pc1FWK77p+kjwAI6R2LMsJz1xh+AEHAYvWwTnFWRproLI6SsYlM4PkyugR5fY4UF3SjzFr5ODXD3igqGwVuKj3y2jU+0NZH3FWLk9M42rVPAvWA8J+F400XXQnMGdefT00p2mLk/Oye5eqjpBx+7uWGA7/rWIF7McF/gbc+w1h2n8DawCEIeBGh9vgMiVuOymtpZuzXMiWUlApdmWOc34h+2vISrjkRMa7j4bA7DlA4H7cdw8/NPMzCg1I9B0C6ueZbc+6YMoLEkHgvd/mrHO6umadsAjVqJr9KAPDP+TaxaOH3/6FAdyyLTTSg0lY9FTlUqo3Oq2E=
  file: build/psalm.phar
