language: php

matrix:
  include:
    - php: 7.0
      env: DEPS="--prefer-lowest --prefer-stable" COVERALLS=""
    - php: 7.0
      env: DEPS="" COVERALLS=""
    - php: 7.1
      env: DEPS="--prefer-lowest --prefer-stable" COVERALLS=""
    - php: 7.1
      env: DEPS="" COVERALLS=""
    - php: 7.2
      env: DEPS="--prefer-lowest --prefer-stable" COVERALLS=""
    - php: 7.2
      env: DEPS="" COVERALLS=true
    - php: nightly
      env: DEPS="" COVERALLS=""
  allow_failures:
    - php: nightly
      env: DEPS="" COVERALLS=""
    - php: 7.1
      env: DEPS="--prefer-lowest --prefer-stable" COVERALLS=""

cache:
  directories:
    - ./vendor

before_install:
    # determine INI file
    - export INI_DIR=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - export INI=$INI_DIR/travis.ini
    # disable default memory limit
    - echo memory_limit = 2G >> $INI
    - if [[ $COVERALLS = "" && -f $INI_DIR/xdebug.ini ]]; then phpenv config-rm xdebug.ini; fi

install:
  - composer --prefer-source $DEPS update

script:
  - vendor/bin/phpunit
  - ./psalm --find-dead-code
  - vendor/bin/phpcs
  - bin/build-phar.sh

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

deploy: # on tag builds with lowest php version (that box supports) and lowest deps
  skip_cleanup: true
  on:
    tags: true
    php: 7.1
    condition: "$DEPS"
  provider: releases
  api_key:
    secure: "K5CTIZ+wqttYUufNyt5oVYnOVkPu+j+qkqCflw0YdGl50TlWT1nBVZripUjMD8GJkxPLybdbw8a3FUs3n4fsHYXoPMS+bbkY264v+2zCzClTOO4EdxvWZB0nNJo7Z7fDatv+LnFg94U+lYcfSZimQn98zB9P0qxFBsF1kKlTm0sTLwx2d1gik9MElnsBVU4yM6CBnWUa0ist8hp7bRKGyQJ1EDkhR2LunIRitbIbrp0dJwS0BDonejl8BCl1dtzeeTXQRtnUDXfcpx+ZFqkRhEdMeH0qaxHf+wBTK6220X2OCFG9tuDDv89GveIM17/f3i8ObCjrhHsM7FAhxIUn3bu0pxcMqPPvNxDrKRGxTV5Fgqyic12cgA+PudIdBTW671K5DEN3F5cpYNwG2oi7A2tVVNSyr01i7rs6bQh/NkEEGX5NECuC/GYXWgK+kIv9E7X0T/U5On9Rar9g8QFiRVMTrkudycbvtZGP4kQV8Ea1+2l5eU+UHhgUoEM0MxrTmemRvyjE5XiERP9jKNafK6o+5xd0nHhlxG2EWnC5xwjSrtcyGZ9Hqm0qg+2XXm65QxczQLDywD419aRGWzVO28zdI5uBVRsPT23DIOnyB9ySaPtJC68sFPyujXuQ9x1sQjmjxlgey1BmnNlXT/OXurBmdJHkNZaPGWkVmKceSuA="
  file: build/psalm.phar
